package blblblbl.cftfocus.binlist.ui.theming

import androidx.compose.ui.graphics.Color

val Red200 = Color(0xfff297a2)
val Red300 = Color(0xffea6d7e)
val Red700 = Color(0xffdd0d3c)
val Red800 = Color(0xffd00036)
val Red900 = Color(0xffc20029)
val Purple200 = Color(0xFFBB86FC)
val Purple500 = Color(0xFF6200EE)
val Purple700 = Color(0xFF3700B3)
val Teal200 = Color(0xFF03DAC5)
val Teal700 = Color(0xFF018786)



val Victoria = Color(0xFF4D5198)
val HalfBacked = Color(0xFF81B7D2)
val PepperMint = Color(0xFFDAF2DC)
val PastelPink = Color(0xFFFFCCE7)
//////////
val md_theme_light_primary = Color(0xFF5156A9)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE0E0FF)
val md_theme_light_onPrimaryContainer = Color(0xFF070764)
val md_theme_light_secondary = Color(0xFF006685)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFBFE9FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001F2A)
val md_theme_light_tertiary = Color(0xFF924276)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD8EB)
val md_theme_light_onTertiaryContainer = Color(0xFF3B002C)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFAFCFF)
val md_theme_light_onBackground = Color(0xFF001F2A)
val md_theme_light_surface = Color(0xFFFAFCFF)
val md_theme_light_onSurface = Color(0xFF001F2A)
val md_theme_light_surfaceVariant = Color(0xFFE4E1EC)
val md_theme_light_onSurfaceVariant = Color(0xFF46464F)
val md_theme_light_outline = Color(0xFF777680)
val md_theme_light_inverseOnSurface = Color(0xFFE1F4FF)
val md_theme_light_inverseSurface = Color(0xFF003547)
val md_theme_light_inversePrimary = Color(0xFFBFC1FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF5156A9)
val md_theme_light_outlineVariant = Color(0xFFC7C5D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFBFC1FF)
val md_theme_dark_onPrimary = Color(0xFF212578)
val md_theme_dark_primaryContainer = Color(0xFF393D8F)
val md_theme_dark_onPrimaryContainer = Color(0xFFE0E0FF)
val md_theme_dark_secondary = Color(0xFF6DD2FF)
val md_theme_dark_onSecondary = Color(0xFF003547)
val md_theme_dark_secondaryContainer = Color(0xFF004D65)
val md_theme_dark_onSecondaryContainer = Color(0xFFBFE9FF)
val md_theme_dark_tertiary = Color(0xFFFFAEDD)
val md_theme_dark_onTertiary = Color(0xFF5A1145)
val md_theme_dark_tertiaryContainer = Color(0xFF752A5D)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD8EB)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F2A)
val md_theme_dark_onBackground = Color(0xFFBFE9FF)
val md_theme_dark_surface = Color(0xFF001F2A)
val md_theme_dark_onSurface = Color(0xFFBFE9FF)
val md_theme_dark_surfaceVariant = Color(0xFF46464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC7C5D0)
val md_theme_dark_outline = Color(0xFF918F9A)
val md_theme_dark_inverseOnSurface = Color(0xFF001F2A)
val md_theme_dark_inverseSurface = Color(0xFFBFE9FF)
val md_theme_dark_inversePrimary = Color(0xFF5156A9)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFBFC1FF)
val md_theme_dark_outlineVariant = Color(0xFF46464F)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF4D5198)

